// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	App        *string              `json:",omitempty"`
	Ingress    *NetworkPolicyConfig `json:",omitempty"`
	Egress     *NetworkPolicyConfig `json:",omitempty"`
	RestartApp *bool                `json:",omitempty"`
	ShipaHost  *string              `json:",omitempty"`
	ShipaToken *string              `json:",omitempty"`
}

// NetworkPolicyConfig is autogenerated from the json schema
type NetworkPolicyConfig struct {
	PolicyMode        *string             `json:",omitempty"`
	CustomRules       []NetworkPolicyRule `json:",omitempty"`
	ShipaRules        []NetworkPolicyRule `json:",omitempty"`
	ShipaRulesEnabled []string            `json:",omitempty"`
}

// NetworkPolicyRule is autogenerated from the json schema
type NetworkPolicyRule struct {
	ID                *string  `json:",omitempty"`
	Enabled           *bool    `json:",omitempty"`
	Description       *string  `json:",omitempty"`
	AllowedFrameworks []string `json:",omitempty"`
}
