// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	App        *string              `json:",omitempty"`
	Ingress    *NetworkPolicyConfig `json:",omitempty"`
	Egress     *NetworkPolicyConfig `json:",omitempty"`
	RestartApp *bool                `json:",omitempty"`
	ShipaHost  *string              `json:",omitempty"`
	ShipaToken *string              `json:",omitempty"`
}

// NetworkPolicyConfig is autogenerated from the json schema
type NetworkPolicyConfig struct {
	PolicyMode        *string             `json:",omitempty"`
	CustomRules       []NetworkPolicyRule `json:",omitempty"`
	ShipaRules        []NetworkPolicyRule `json:",omitempty"`
	ShipaRulesEnabled []string            `json:",omitempty"`
}

// NetworkPolicyRule is autogenerated from the json schema
type NetworkPolicyRule struct {
	ID                *string       `json:",omitempty"`
	Enabled           *bool         `json:",omitempty"`
	Description       *string       `json:",omitempty"`
	Ports             []NetworkPort `json:",omitempty"`
	Peers             []NetworkPeer `json:",omitempty"`
	AllowedApps       []string      `json:",omitempty"`
	AllowedFrameworks []string      `json:",omitempty"`
}

// NetworkPort is autogenerated from the json schema
type NetworkPort struct {
	Protocol *string `json:",omitempty"`
	Port     *int    `json:",omitempty"`
}

// NetworkPeer is autogenerated from the json schema
type NetworkPeer struct {
	PodSelector       *NetworkPeerSelector `json:",omitempty"`
	NamespaceSelector *NetworkPeerSelector `json:",omitempty"`
	IPBlock           []string             `json:",omitempty"`
}

// NetworkPeerSelector is autogenerated from the json schema
type NetworkPeerSelector struct {
	MatchLabels      []Pair               `json:",omitempty"`
	MatchExpressions []SelectorExpression `json:",omitempty"`
}

// Pair is autogenerated from the json schema
type Pair struct {
	Key   *string `json:",omitempty"`
	Value *string `json:",omitempty"`
}

// SelectorExpression is autogenerated from the json schema
type SelectorExpression struct {
	Key      *string  `json:",omitempty"`
	Operator *string  `json:",omitempty"`
	Values   []string `json:",omitempty"`
}
