// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Name        *string      `json:",omitempty"`
	Description *string      `json:",omitempty"`
	Teamowner   *string      `json:",omitempty"`
	Framework   *string      `json:",omitempty"`
	Plan        *Plan        `json:",omitempty"`
	Units       []Unit       `json:",omitempty"`
	Cname       []string     `json:",omitempty"`
	IP          *string      `json:",omitempty"`
	Org         *string      `json:",omitempty"`
	Entrypoints []Entrypoint `json:",omitempty"`
	Routers     []Router     `json:",omitempty"`
	Lock        *Lock        `json:",omitempty"`
	Tags        []string     `json:",omitempty"`
	Platform    *string      `json:",omitempty"`
	Status      *string      `json:",omitempty"`
	Error       *string      `json:",omitempty"`
	ShipaHost   *string      `json:",omitempty"`
	ShipaToken  *string      `json:",omitempty"`
}

// Plan is autogenerated from the json schema
type Plan struct {
	Name     *string  `json:",omitempty"`
	Memory   *int     `json:",omitempty"`
	Swap     *int     `json:",omitempty"`
	CPUShare *int     `json:",omitempty"`
	Default  *bool    `json:",omitempty"`
	Public   *bool    `json:",omitempty"`
	Org      *string  `json:",omitempty"`
	Teams    []string `json:",omitempty"`
}

// Unit is autogenerated from the json schema
type Unit struct {
	ID          *string  `json:",omitempty"`
	Name        *string  `json:",omitempty"`
	AppName     *string  `json:",omitempty"`
	ProcessName *string  `json:",omitempty"`
	Type        *string  `json:",omitempty"`
	IP          *string  `json:",omitempty"`
	Status      *string  `json:",omitempty"`
	Version     *string  `json:",omitempty"`
	Org         *string  `json:",omitempty"`
	HostAddr    *string  `json:",omitempty"`
	HostPort    *string  `json:",omitempty"`
	Address     *Address `json:",omitempty"`
}

// Address is autogenerated from the json schema
type Address struct {
	Scheme      *string `json:",omitempty"`
	Host        *string `json:",omitempty"`
	Opaque      *string `json:",omitempty"`
	User        *string `json:",omitempty"`
	Path        *string `json:",omitempty"`
	RawPath     *string `json:",omitempty"`
	ForceQuery  *bool   `json:",omitempty"`
	RawQuery    *string `json:",omitempty"`
	Fragment    *string `json:",omitempty"`
	RawFragment *string `json:",omitempty"`
}

// Entrypoint is autogenerated from the json schema
type Entrypoint struct {
	Cname  *string `json:",omitempty"`
	Scheme *string `json:",omitempty"`
}

// Router is autogenerated from the json schema
type Router struct {
	Name    *string `json:",omitempty"`
	Type    *string `json:",omitempty"`
	Address *string `json:",omitempty"`
	Default *bool   `json:",omitempty"`
}

// Lock is autogenerated from the json schema
type Lock struct {
	Locked      *bool   `json:",omitempty"`
	Reason      *string `json:",omitempty"`
	Owner       *string `json:",omitempty"`
	AcquireDate *string `json:",omitempty"`
}
