// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Name         *string        `json:",omitempty"`
	Framework    *string        `json:",omitempty"`
	Containers   []JobContainer `json:",omitempty"`
	Policy       *Policy        `json:",omitempty"`
	BackoffLimit *int           `json:",omitempty"`
	Completions  *int           `json:",omitempty"`
	Parallelism  *int           `json:",omitempty"`
	Suspend      *bool          `json:",omitempty"`
	Description  *string        `json:",omitempty"`
	Team         *string        `json:",omitempty"`
	Type         *string        `json:",omitempty"`
	Version      *string        `json:",omitempty"`
	ShipaHost    *string        `json:",omitempty"`
	ShipaToken   *string        `json:",omitempty"`
}

// JobContainer is autogenerated from the json schema
type JobContainer struct {
	Command []string `json:",omitempty"`
	Image   *string  `json:",omitempty"`
	Name    *string  `json:",omitempty"`
}

// Policy is autogenerated from the json schema
type Policy struct {
	RestartPolicy *string `json:",omitempty"`
}
