// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	App            *string `json:",omitempty"`
	Image          *string `json:",omitempty"`
	PrivateImage   *bool   `json:",omitempty"`
	RegistryUser   *string `json:",omitempty"`
	RegistrySecret *string `json:",omitempty"`
	Steps          *int    `json:",omitempty"`
	StepWeight     *int    `json:",omitempty"`
	StepInterval   *string `json:",omitempty"`
	Port           *int    `json:",omitempty"`
	Detach         *bool   `json:",omitempty"`
	Message        *string `json:",omitempty"`
	ShipaHost      *string `json:",omitempty"`
	ShipaToken     *string `json:",omitempty"`
}
