// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	App        *string `json:",omitempty"`
	Cname      *string `json:",omitempty"`
	Scheme     *string `json:",omitempty"`
	ShipaHost  *string `json:",omitempty"`
	ShipaToken *string `json:",omitempty"`
}
